categories:
  - title: ":boom: Breaking Changes"
    label: "breaking"
  - title: ":rocket: Features"
    label: "enhancement"
  - title: ":fire: Removals and Deprecations"
    label: "removal"
  - title: ":beetle: Fixes"
    label: "bug"
  - title: ":racehorse: Performance"
    label: "performance"
  - title: ":books: Documentation"
    label: "documentation"
  - title: ":hammer: Internals"
    labels:
      - "refactoring"
      - "style"
      - "ci"
      - "testing"
      - "dependencies"

exclude-labels:
  - "skip-changelog"

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"

template: |
  ## Changes

  $CHANGES

  ---

  ## New contributors
  $NEW_CONTRIBUTORS

   **Full Changelog**: $PREVIOUS_TAG...$RESOLVED_VERSION
